### ISSUE TITLE
Glitch pada Chart dashboard

### ISSUE THREAD

**Issue by KNobHack** [AyuMuhafilah/absensi_nezal#2]
@AyuMuhafilah aya nu salah pas nampilkeun data di chart 😅 

Bulan nu teu terdapat data Sakit, Izin atau Alpa bakal ngageser data di bulan setelahna ka belakang.

Misal data na :
Mei | Juni
---- | -----
Sakit 0 | Sakit 4
Izin 1 | Izin 1

Tapi kalah tampil di chart na kieu :
Mei | Juni
---- | -----
Sakit 4 | null
Izin 1 | Izin 1

Salahna aya di commit ti urang 🙏

**Comment by AyuMuhafilah** [comment]
Nya Siapp

**Comment by KNobHack** [comment]
Gs di benerkeun yu, tinggal di merge pull request #5
